[package]
name = "exchange"
version = "0.1.0"
authors = ["sergiy"]

[dependencies]
exonum = "0.3.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bodyparser = "0.7.0"
router = "0.5.1"
iron = "0.5.1"
